# Generated by Django 4.2.2 on 2023-06-10 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Salary', models.FloatField()),
                ('Description', models.CharField(max_length=80)),
                ('Designation', models.CharField(max_length=80)),
                ('Manager', models.CharField(max_length=70)),
                ('DepName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dep.dep_system')),
            ],
        ),
    ]
