# Generated by Django 4.2.2 on 2023-06-20 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_Mod',
            fields=[
                ('Manager', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Salary', models.FloatField()),
                ('Description', models.CharField(max_length=80)),
                ('Designation', models.CharField(max_length=80)),
                ('DepName', models.ForeignKey(db_column='DepName', on_delete=django.db.models.deletion.CASCADE, to='Dep.dep_system', to_field='DepName')),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emp.manager_mod')),
            ],
        ),
    ]
