# Generated by Django 4.2.1 on 2023-06-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dep_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepName', models.CharField(max_length=80)),
                ('Department_Head', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Salary', models.FloatField()),
                ('Description', models.CharField(max_length=80)),
                ('Designation', models.CharField(max_length=80)),
                ('Manager', models.CharField(max_length=70)),
                ('DepName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.dep_system')),
            ],
        ),
    ]
