# Generated by Django 4.2.2 on 2023-06-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dep_system',
            fields=[
                ('DepName', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('Department_Head', models.CharField(max_length=80)),
            ],
        ),
    ]
